### ISSUE TITLE
WWW_DIR constant needed in diagnostics panel

### ISSUE THREAD

**Issue by echo511** [iPublikuj/assets-loader#1]
Hi,
is shortening paths really required in https://github.com/iPublikuj/assets-loader/blob/master/src/IPub/AssetsLoader/Diagnostics/Panel.php#L81?

It won't even work properly when defining in bootstrap.php like this:

``` php
define('WWW_DIR', __DIR__ . '/../');
```

**Comment by akadlec** [comment]
Yes, you are right. This is from previous version, where static files were stored in document root. Maybe there could be another route for serving this files, if it is necessary.

**Comment by echo511** [comment]
I was thinking about deleting the mentioned row from source code.
