### ISSUE TITLE
Class 'lessc' not found

### ISSUE THREAD

**Issue by ghost** [iPublikuj/assets-loader#3]
does it depends on other class or command line tool?

File: ...\src\IPub\AssetsLoader\Filters\Files\LessFilter.php:70

60:  
61:        /**
62:         \* Get less compiler
63:         *
64:         \* @return \lessc
65:         */
66:        protected function getLessC()
67:        {
68:            // Lazy loading
69:            if (!$this->lc) {
70:              $this->lc = new \lessc(); 
71:            }
72:  
73:            return $this->lc;
74:        }

**Comment by akadlec** [comment]
yes it depends on other package: leafo/lessphp

**Comment by akadlec** [comment]
Added missing dependency
